export const CART_ADD_BOOK = 'CART_ADD_BOOK'
export const CART_REMOVE_BOOK = 'CART_REMOVE_BOOK'
export const CART_RECORD_SHIPPING_ADDRESS = 'CART_RECORD_SHIPPING_ADDRESS'
export const CART_RECORD_PAYMENT_METHOD = 'CART_RECORD_PAYMENT_METHOD'