export const ORDER_ADDED_REQUEST = 'ORDER_ADDED_REQUEST'
export const ORDER_ADDED_SUCCESS = 'ORDER_ADDED_SUCESS'
export const ORDER_ADDED_FAIL = 'ORDER_ADDED_FAIL'

export const ORDER_INFO_REQUEST = 'ORDER_INFO_REQUEST'
export const ORDER_INFO_SUCCESS = 'ORDER_INFO_SUCESS'
export const ORDER_INFO_FAIL = 'ORDER_INFO_FAIL'