export const ORDER_ADDED_REQUEST = 'ORDER_ADDED_REQUEST'
export const ORDER_ADDED_SUCCESS = 'ORDER_ADDED_SUCESS'
export const ORDER_ADDED_FAIL = 'ORDER_ADDED_FAIL'

export const ORDER_INFO_REQUEST = 'ORDER_INFO_REQUEST'
export const ORDER_INFO_SUCCESS = 'ORDER_INFO_SUCESS'
export const ORDER_INFO_FAIL = 'ORDER_INFO_FAIL'

export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST'
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCESS'
export const ORDER_PAYMENT_FAIL = 'ORDER_PAYMENT_FAIL'
export const ORDER_PAYMENT_CLEAN = 'ORDER_PAYMENT_CLEAN'