export const USER_SIGIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS'
export const USER_INFO_FAIL = 'USER_INFO_FAIL'

export const USER_UPDATE_ACC_REQUEST = 'USER_UPDATE_ACC_REQUEST'
export const USER_UPDATE_ACC_SUCCESS = 'USER_UPDATE_ACC_SUCCESS'
export const USER_UPDATE_ACC_FAIL = 'USER_UPDATE_ACC_FAIL'
export const USER_UPDATE_ACC_CLEAN = 'USER_UPDATE_ACC_CLEAN'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_CLEAN = 'USER_LIST_CLEAN'







